dist: bionic
language: go
go:
- 1.13.x
os:
- linux
services:
- docker
# safelist
branches:
  only:
  - master
# install: go mod download
script: bash scripts/build-hello.sh
git:
  quiet: true
  depth: 10
env:
- GO111MODULE=on
