dist: bionic
language: go
go:
- 1.13.x
os:
- linux
# safelist
branches:
  only:
  - master
# install: go mod download
script: go build -o hello/hello ./hello/
git:
  quiet: true
  depth: 10
env:
- GO111MODULE=on
